### ISSUE TITLE
[suggestion] prevent [send to] feature removing negative prompt

### ISSUE THREAD

**Issue by wansf3** [Malisius/booru2prompt#1]
many users uses NAI default negative prompt "lowres, bad anatomy, bad hands, text, error, missing fingers, extra digit, fewer digits, cropped, worst quality, low quality, normal quality, jpeg artifacts, signature, watermark, username, blurry, artist name", but using this extension will wipe them out so i have to copy&paste everytime i use, please fix

**Comment by Malisius** [comment]
Yeah I've been copying them back in myself each time so far, which isn't ideal. I'll add an option to retain the negative prompt in the next update.

**Comment by Malisius** [comment]
It's not great, but this has been addressed in v1.1
